version: '3.6'

services:
  web:
    image: alpine:3.11
    container_name: the-gear-of-seasons_web
    hostname: the-gear-of-seasons_web
    restart: always
    networks:
      - planet-link
    volumes:
      - ./:/gear
    working_dir: /gear
    entrypoint:
      - /gear/the-gear-of-seasons
      - -shelf
      - /gear/_shelf
      - -cache
      - /gear/_cache
      - -listen-omote
      - :8080
      - -listen-ura
      - :8081
    expose:
      - "8080"
      - "8081"

networks:
  planet-link:
    external: true